[knx]
connection   = tunneling
gateway_ip   = 192.168.88.14
gateway_port = 3671
; local_ip   = 192.168.1.50

[control]
transport = cli
host      = 0.0.0.0
port      = 8080

;[outlet0]
;type     = outlet
;Action   = 3/1/1
;Status   = 2/2/2
;Inverted = True

;[dimmer_kitchen]
;type      = dimmer
;Action    = 1/2/1
;ActionDim = 1/2/2
;Status    = 2/2/1
;StatusDim = 2/2/2

;[thermostat_room]
;type           = thermostat
;ActionOnOff    = 1/1/6
;StatusOnOff    = 1/1/7
;ActionSetpoint = 1/1/1
;StatusSetpoint = 1/1/2
;StatusCurrent  = 1/1/3
;ActionMode     = 1/1/4
;StatusMode     = 1/1/5
;StatusSeason   = 2/3/5
;Season         = winter
;Mode           = off
;Setpoint       = 21.0
;Current        = 19.0
;CycleSec       = 30

[ac_livingroom]
type           = air_conditioner
ActionOnOff    = 2/1/6
StatusOnOff    = 2/1/7
ActionSetpoint = 2/1/1
StatusSetpoint = 2/1/2
StatusCurrent  = 2/1/3
ActionMode     = 2/1/4
StatusMode     = 2/1/5
;StatusSeason   = 2/1/8
;Season         = summer
ActionFan      = 2/1/9
StatusFan      = 2/1/10
Mode           = off
Setpoint       = 24.0
Current        = 27.0
Fan            = 50
CycleSec       = 30

;[air_quality0]
;type        = air_quality_sensor
;StatusAQI   = 3/0/1
;StatusCH2O  = 3/0/2
;StatusTVOC  = 3/0/3
;StatusPM1   = 3/0/4
;StatusPM2_5 = 3/0/5
;StatusPM10  = 3/0/6
;StatusCO2   = 3/0/7
;AQI         = 50
;CO2         = 400
;CycleSec    = 60
